### ISSUE TITLE
error "Unsupported value of __FLT_EVAL_METHOD__."

### ISSUE THREAD

**Issue by maygpedersen** [rhdtownsend/msg#24]
Hi Rich and Aaron,

I am running into a similar problem as amiszuda when trying to install msg-1.3.

**The following is my system setup:**

- Apple M1 Pro, Sequoia 15.3.1
- MESA SDK version: 24.10.1

This is my minimal step-by-step approach to reproduce the error

```
$ tar xf msg-1.3.tar.gz
$ export MSG_DIR=/Users/mped4857/Software/msg-1.3
$ export MESASDK_ROOT=/Applications/mesasdk
$ source $MESASDK_ROOT/bin/mesasdk_init.sh
$ conda create --name msg_py1.1 python numpy cython matplotlib pandas
$ conda activate msg_py1.1
$ cd $MSG_DIR
$ make -j &> output1.txt
```

This give the following error (full output in attached output1.txt file)

```
In file included from /Users/mped4857/Software/miniconda3/envs/msg_py1.1/include/python3.13/Python.h:22,
                 from ../src/cython/pycmsg.c:6:
/Applications/mesasdk/bin/../sysroot/usr/include/math.h:54:5: error: #error "Unsupported value of __FLT_EVAL_METHOD__."
   54 | #   error "Unsupported value of __FLT_EVAL_METHOD__."

```

[output1.txt](https://github.com/user-attachments/files/18930306/output1.txt)

Just like amiszuda, I do not have a pycmsg.c file in the build/ directory.

Next I tried renaming src/cython/pycmsg.c to src/cython/pycmsg.c.saved as you suggested and ran the following

```
$ make clean
$ make -j &> output2.txt
```

[output2.txt](https://github.com/user-attachments/files/18930329/output2.txt)

This got rid of a lot of other errors, but the main one still persists. 

Do you have any further suggestions for how to solve this? 

Please let me know if you prefer I repost this in the issue that amiszuda created instead.

Best,
May

**Comment by rhdtownsend** [comment]
Hi May —

I’m able to reproduce this error (or something similar) on my Mac. I’ll be posting a new SDK shortly, that should fix the problem.

cheers,

Rich

**Comment by rhdtownsend** [comment]
Hi May --

Here's a link to the SDK:

**Comment by maygpedersen** [comment]
Hi Rich,

Thank you for the swift response!

I just tried installing MSG with the new SDK, but it looks like the problem still persists for me, see attached output file.

[output3.txt](https://github.com/user-attachments/files/18974464/output3.txt)

Cheers,
May

**Comment by maygpedersen** [comment]
Sure, I get this output

```
(msg_py1.1) mped4857@AKNXNLFX74K msg-1.3 % mesasdk_version
aarch64-macos-25.2.1
```

**Comment by rhdtownsend** [comment]
Thanks, May!

Next question: can you post the output from ‘ls -l /Library/Developer/CommandLineTools/SDKs/‘

cheers,

Rich

> On Feb 25, 2025, at 8:32 PM, May Gade Pedersen ***@***.***> wrote:
> 
> Sure, I get this output
> (msg_py1.1) ***@***.*** msg-1.3 % mesasdk_version
> aarch64-macos-25.2.1
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>
> maygpedersen left a comment (rhdtownsend/msg#24)
> Sure, I get this output
> (msg_py1.1) ***@***.*** msg-1.3 % mesasdk_version
> aarch64-macos-25.2.1
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

--
Rich Townsend • Professor of Astronomy
Astronomy Department • University of Wisconsin-Madison
Phone: 608-262-1752 • E-mail: ***@***.***

**Comment by maygpedersen** [comment]
Sure! Here you go
```

(msg_py1.1) mped4857@AKNXNLFX74K msg-1.3 % ls -l /Library/Developer/CommandLineTools/SDKs/
total 0
lrwxr-xr-x  1 root  wheel   14  6 Dec 16:12 MacOSX.sdk -> MacOSX15.1.sdk
drwxr-xr-x  7 root  wheel  224  8 Jul  2024 MacOSX14.5.sdk
lrwxr-xr-x  1 root  wheel   14  6 Dec 16:11 MacOSX14.sdk -> MacOSX14.5.sdk
drwxr-xr-x  7 root  wheel  224 11 Oct 10:11 MacOSX15.1.sdk
lrwxr-xr-x  1 root  wheel   14  6 Dec 16:10 MacOSX15.sdk -> MacOSX15.1.sdk
```

Cheers,
May

**Comment by maygpedersen** [comment]
Hi Rich,

Got it! Just tried doing the installation again with the new SDK and it does look like the "FLT_EVAL_METHOD" error is gone! The other ones still remain.

```
(msg_py1.1) mped4857@AKNXNLFX74K msg-1.3 % mesasdk_version
aarch64-macos-25.2.2
(msg_py1.1) mped4857@AKNXNLFX74K msg-1.3 % make -j &> output4.txt
```

[output4.txt](https://github.com/user-attachments/files/19018256/output4.txt)

Cheers,
May

**Comment by rhdtownsend** [comment]
That's really encouraging! Next step, try adding the following near the top of the file src/incude/pycmsg.h (just after the #include "stdbool.h" line):

#if defined(I)
  #undef I
#endif

Then, make sure you have installed the cython package (using conda, pip, etc), and delete the file src/cython/pycmsg.c. Do "make clean", and then build as usual.

**Comment by maygpedersen** [comment]
Got it. So I don't have the pycmsg.h file, but a cmsg.h file instead

```
(msg_py1.1) mped4857@AKNXNLFX74K msg-1.3 % ls $MSG_DIR/src/include
cmsg.h
```

Do you want me to try to add it to this file instead?

**Comment by rhdtownsend** [comment]
Oops yes, my bad!

> On Feb 27, 2025, at 11:15 PM, May Gade Pedersen ***@***.***> wrote:
> 
> Got it. So I don't have the pycmsg.h file, but a cmsg.h file instead
> (msg_py1.1) ***@***.*** msg-1.3 % ls $MSG_DIR/src/include
> cmsg.h
> 
> Do you want me to try to add it to this file instead?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>
> maygpedersen left a comment (rhdtownsend/msg#24)
> Got it. So I don't have the pycmsg.h file, but a cmsg.h file instead
> (msg_py1.1) ***@***.*** msg-1.3 % ls $MSG_DIR/src/include
> cmsg.h
> 
> Do you want me to try to add it to this file instead?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

--
Rich Townsend • Professor of Astronomy
Astronomy Department • University of Wisconsin-Madison
Phone: 608-262-1752 • E-mail: ***@***.***

**Comment by maygpedersen** [comment]
Hi Rich,

I followed your suggestions, and it looks like MSG got installed correctly now!

`(msg_py1.1) mped4857@AKNXNLFX74K msg-1.3 % make -j &> output5.txt`

[output5.txt](https://github.com/user-attachments/files/19043092/output5.txt)

I did the test as well and it looks like all of them passed as well.

`(msg_py1.1) mped4857@AKNXNLFX74K msg-1.3 % make test &> output6.txt`

[output6.txt](https://github.com/user-attachments/files/19043097/output6.txt)

Installing pymsg also appears to have run smoothly

`pip install $MSG_DIR/python &> output7.txt`

[output7.txt](https://github.com/user-attachments/files/19043136/output7.txt)

Thank you very much for your help!

Cheers,
May
